### ISSUE TITLE
Error with `Parent` class

### ISSUE THREAD

**Issue by julienfastre** [secit-pl/schema-org#2]
While creating a new `Person` class: 

> Symfony\Component\Debug\Exception\FatalErrorException:
> Compile Error: Cannot use 'SecIT\SchemaOrg\Mapping\Property\Parent' as class name as it is reserved
> 
>   at vendor/secit-pl/schema-org/SchemaOrg/Mapping/Type/Person.php:1207

Maybe a reserved class name since php 7 ?

**Comment by secit-pl** [comment]
New version released (3.3.2). Could you please try to use a new (suffixed) class names and confirm that your code is working on PHP 7?

**Comment by secit-pl** [comment]
@julienfastre is your problem solved?

**Comment by julienfastre** [comment]
i am sorry, I could not work on this part of our app. I will go on on this the first week of December.

Thanks.

**Comment by secit-pl** [comment]
@julienfastre is your problem solved?

**Comment by secit-pl** [comment]
The problem should be solved
